### PR TITLE
Update to latest OpenVR SDK

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Todo:
- [x] Update driver.
- [x] Test / fix current functionality on the HMDs & controllers currently supported.
    - [x] Oculus Rift via SteamVR using the OpenVR plugin
    - [x] Vive with Vive controllers
    - [x] WMR with WMR  controllers

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
#### So Far

I've updated the OpenVR plugin to use the latest OpenVR SDK - version 1.11.11 - and tested as far as I can in my development environment.

My development environment is Windows using SteamVR + Oculus as if it were a Vive (i.e., using the OpenVR plugin instead of the Oculus plugin).
This can be done by doing `set HIFI_DEBUG_OPENVR=1` in a command prompt and starting up Interface.exe in the same command prompt.
The HMD display works but the controllers don't - controller mapping errors reported in the program log.

Two areas needed fixing in order to build with the latest SDK:
- `vrOverlay` configuration: I tested the fix by programmatically causing the overlay to display, to check that it displays OK.
- Reporting preferred audio I/O devices: The devices weren't reporting on K2 with SteamVR + Oculus-as-Vive but I've codes the probable fix, and have also included two `FIXME`s of possible improvements.


#### Next Step: Test/Fix with Vive.

- HMD displays OK, same as current K2 release.
- Controllers work OK, same as current K2 release.
- Preferred audio I/O devices reported OK.
- Address `FIXME`s in `getPreferredAudioInDevice()` and `getPreferredAudioOutDevice()`.

To test that the audio I/O devices are reported you can run the following script which periodically reports their values to the program log. Note that values are expected to be `""` in desktop mode but should contain non-empty values in HMD mode.

[reportHMDAudioDevices.zip](https://github.com/kasenvr/project-athena/files/4590734/reportHMDAudioDevices.zip)

The values should be those set in the SteamVR settings: Click the menu icon top left of the SteamVR panel, select "Settings", then "Audio", and there you can set settings that map to the audio keys in the `k_pch_audio_Section` section of openvr.h.
Check that the record / playback values reported are around the correct way. (The original code appeared to have them switched.)

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR335/ProjectAthena-Alpha-PR335-44a29c4_42036b27.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR335/ProjectAthena-Alpha-PR335-44a29c4.tar_42036b27.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR335/ProjectAthena-Alpha-PR335-44a29c4.tar_42036b27.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR335/ProjectAthena-Alpha-PR335-44a29c4_42036b27.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR335/ProjectAthena-Alpha-PR335-44a29c4_42036b27.exe

**Comment by ctrlaltdavid** [comment]
Languagelovr tested Vive with the PR and K2 builds: for both the test script reports the preferred audio I/O devices as "". So no change in behaviour in this PR; there appears to be a pre-existing bug with the devices reported for Vive.

**Comment by languagelovr** [comment]
I've tested again using another PC with no audio problems and everything appears to be working as far as I could tell. I sent ctrlaltdavid the log files from this PR335 as well as the K2 build for comparison.

**Comment by kasenvr** [comment]
I am currently testing the WMR side of things. I am also using my Valve Index Controllers in conjunction with my Samsung Odyssey+ for testing.

**Comment by ctrlaltdavid** [comment]
HMD.preferredAudioInput() and Output() API calls don't work in the OpenVR HMD plugin. This was the case in the 0.86.0-based K2 release and is still the case in this PR, despite trying varios things and extensive testing. It's not critical to correct operation (the calls are just provided in the API and aren't used in any Vircadia scripts) so I've lodge a bug report to address sometime later: https://github.com/kasenvr/project-athena/issues/374

**Comment by SilverfishVR** [comment]
tested with steamVR 1.11.13 (Valve index + index controllers)

everything, including audio switching, seem every bit as working/broken as K2, so I guess, all good.

**Comment by kasenvr** [comment]
Can confirm, everything is working/broken as expected on my end as well.
Samsung Odyssey+ w/ Valve Index Controllers.

**Pull request merged**
