### PR TITLE
Fix server logs filling up with "/"s

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Issue: https://github.com/kasenvr/project-athena/issues/147

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Testing

1. Reproduce the problem with a previous version of the Windows Sandbox running on your PC:
- Run the Sandbox.
- From the system tray icon, select "View Logs".
- Select the "Assignment Clients" tab.
- There should be repeated messages, "Trying to go to URL "hifi://///////"" with an ever increasing number of "/"s.

2. Check that the problem is fixed with the Windows Sandbox from the PR running on your PC.
- The number of "/"s in the messages should stay at 2.

3. In Interface, check that you can use the GOTO app to successfully navigate to ThePalace using the following URLs typed into the "Type domain address here" text box:
- thepalace
- hifi:thepalace
- hifi:/thepalace
- hifi://thepalace

**Comment by MarcusLlewellyn** [comment]
Unofficial PR build for Windows available here: [ProjectAthena-Alpha-PR175-fae237f.exe](https://drive.google.com/file/d/1PuAUgXDjyf6A-7iGj_FLs5wQ9-Bwmtii/view?usp=sharing)

**Comment by MarcusLlewellyn** [comment]
I can confirm that this is fixed on Ubuntu 18.04.4

**Comment by ctrlaltdavid** [comment]
Test on Windows needed.

**Pull request merged**
