### PR TITLE
Updated the Explore app UI

### PR DESCRIPTION
**Pull request by Madders**
Made changes to how the explore app looks and functions.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR654/Vircadia-Alpha-PR654-588c96c.tar_44138184.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR654/Vircadia-Alpha-PR654-588c96c_44138184.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR654/Vircadia-Alpha-PR654-588c96c.tar_44138184.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR654/Vircadia-Alpha-PR654-588c96c_44138184.dmg

**Comment by SilverfishVR** [comment]
Is there a reason there is no windows build of this?

**Comment by kasenvr** [comment]
Well you see, it's an OSX/Linux timed exclusive.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR654/Vircadia-Alpha-PR654-588c96c.tar_44138184.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR654/Vircadia-Alpha-PR654-588c96c_44138184.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR654/Vircadia-Alpha-PR654-588c96c.tar_44138184.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR654/Vircadia-Alpha-PR654-588c96c_44138184.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR654/Vircadia-Alpha-PR654-588c96c_44138184.exe

**Comment by SilverfishVR** [comment]
Seems to work as intended, and it looks nice. A few notes:
1. it is missing a home button.
2. would be nice if the add location page also had all the fields available, like avatar count distance.
3. ideally, search and address would be one input field, searching the list as you type, but take you to the specified address if you press return or click the "go" icon.

also, what is the "explore" button supposed to do?

**Comment by Madders** [comment]
@SilverfishVR To adress your points:

1. The home button should be there, but only appears if you have a home location set. This was by request on the discord. Have you set your home location? If so, and it's still not showing then I'll have a check into why it's not displaying.
2. When written those were the only settings being exposed by the location storage backend. If there are now more options, then support can be added for them. If these options aren't yet part of the backend, then we'd need to add support there too.
3. The UI can be easily modified to work like that. If the consensus is to work that way then I could make the amendments.

The Explore button is for future support. My full design includes bottom "tab" buttons for "Explore", "Bookmarks" "Events" and "Settings", but we wanted to get a first version in now so submitted ahead of the other tabs being completed.

**Comment by kasenvr** [comment]
image
Creating a beacon using "Add Location" currently puts in the wrong script URL it would seem.

**Comment by Madders** [comment]
@kasenvr haven't been able to actually test it, but I believe latest commit should fix that.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR654/Vircadia-Alpha-PR654-66cabb0_86b2f189.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR654/Vircadia-Alpha-PR654-66cabb0.tar_86b2f189.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR654/Vircadia-Alpha-PR654-66cabb0.tar_86b2f189.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR654/Vircadia-Alpha-PR654-66cabb0_86b2f189.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR654/Vircadia-Alpha-PR654-66cabb0_86b2f189.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR654/Vircadia-Alpha-PR654-7530153.tar_085bdf00.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR654/Vircadia-Alpha-PR654-7530153_085bdf00.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR654/Vircadia-Alpha-PR654-7530153.tar_085bdf00.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR654/Vircadia-Alpha-PR654-7530153_085bdf00.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR654/Vircadia-Alpha-PR654-7530153_085bdf00.exe

**Comment by kasenvr** [comment]
This app was very uniquely put together as a literal single page app (it's one file), but it all seems... to work. So I'm OK with the code for now. The indenting style is also unique. :D

I tested it a bit in the course of applying some modifications.

**Review by kasenvr — APPROVED** [review]

**Pull request merged**
