### PR TITLE
Removed "Marketplace Item Tester" from developer menu.(interface)

### PR DESCRIPTION
**Pull request by Nex-Pro**
To test, check that "Test Marketplace Item" is not present on the developer menu

### CODE REVIEW

**Comment by Nex-Pro** [comment]
Currently code is simply commented out. We should probably remove the code and the referenced QML files for the app.

**Comment by thoys** [comment]
I see this code comments a line in the wallet code.  Since the menu item gets created in the wallet, wouldn't it make more sense to just exclude the wallet from the default scripts?

**Comment by Nex-Pro** [comment]
@thoys hence my comment

**Comment by Nex-Pro** [comment]
but this to remove the tester

**Comment by Nex-Pro** [comment]
we don't want to remove the wallet AFAIK

**Comment by MarcusLlewellyn** [comment]
From a style standpoint, the ugly thing here is the giant block of commented code. I'd remove the block comments at lines 635 and 665. As long as the functions called from within that block are commented out  (lines 704 and 728), maybe with an additional `// UNDONE: <REASON>` task comment for those lines, I'd call it okay.

Although we do not want to remove the wallet at this point, it will inevitably go away in the future, so sweating the details probably isn't worth our time.

**Comment by thoys** [comment]
This menu item will only display for people that run the wallet script. It is a thing that only shows up in the developer menu. Why does it bother you?

**Comment by Nex-Pro** [comment]
Seems this test wasn't needed.

**Pull request closed without merging**
