### PR TITLE
Tidy JSON relative URLs importing code

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Per CR of https://github.com/kasenvr/project-athena/pull/586 .

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Testing

Per https://github.com/kasenvr/project-athena/pull/586 .

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR672/Vircadia-Alpha-PR672-8e9dbe8_4214182b.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR672/Vircadia-Alpha-PR672-8e9dbe8.tar_4214182b.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR672/Vircadia-Alpha-PR672-8e9dbe8.tar_4214182b.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR672/Vircadia-Alpha-PR672-8e9dbe8_4214182b.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR672/Vircadia-Alpha-PR672-8e9dbe8_4214182b.exe

**Review by daleglass — APPROVED** [review]

**Comment by HifiExperiments** [comment]
we should add a TODO (or implement the correct solution) for the `textures` property for models, which also isn't just a single URL

**Comment by ctrlaltdavid** [comment]
Added "FIXME" to code for missing handling of Model's "textures" and "originalTexturs" properties and submitted issue: https://github.com/kasenvr/project-athena/issues/674

**Comment by HifiExperiments** [comment]
`originalTextures` might get parsed from the model on each load, I'm not sure how that works when loading from JSON tbh, but this looks good either way!

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR672/Vircadia-Alpha-PR672-3b24224_2bfdaa31.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR672/Vircadia-Alpha-PR672-3b24224.tar_2bfdaa31.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR672/Vircadia-Alpha-PR672-3b24224.tar_2bfdaa31.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR672/Vircadia-Alpha-PR672-3b24224_2bfdaa31.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR672/Vircadia-Alpha-PR672-3b24224_2bfdaa31.exe

**Comment by Aitolda** [comment]
Tested per [#586](https://github.com/kasenvr/project-athena/pull/586).

All objects loaded as expected.

**Pull request merged**
