### PR TITLE
Use newer opus to fix illegal instruction in libopusCodec.so

### PR DESCRIPTION
**Pull request by daleglass**
This will build the very latest Opus available (May 30 2020). The absolute
minimum version of Opus is commit 927de8453c502586c03e25c169ec08f2a93ebc02,
released on April 21, 2020.

This incorporates a fix for xiph/opus#154

### CODE REVIEW

**Comment by daleglass** [comment]
When the bug is triggered, the audio mixer will crash with something like:

    trap invalid opcode ip:7f7e141b991e sp:7f7e07ffe850 error:0 in libopusCodec.so[7f7e1418c000+65000]

The crash will be noticed by the domain, which will log:

    
Jun 07 03:03:53 MotoFckr9k-Server assignment-client[1127]: [06/07 03:03:53] [CRITICAL] [default] [1127] [assignment-client-monitor] Child process 1384 on port 0has crashed with exit code 4. Removed from internal map.
motofckr9k@MotoFckr9k-Server:~$


Since this PR fixes a bug that happens on old hardware, it should be tested on hardware that's as old as possible. For instance, on a Ryzen 9 it doesn't happen. It does happen on an 
AMD Athlon(tm) II X4 635.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR429/Vircadia-Alpha-PR429-f6680cd_7dd5a277.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR429/Vircadia-Alpha-PR429-f6680cd.tar_7dd5a277.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR429/Vircadia-Alpha-PR429-f6680cd.tar_7dd5a277.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR429/Vircadia-Alpha-PR429-f6680cd_7dd5a277.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR429/Vircadia-Alpha-PR429-f6680cd_7dd5a277.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR429/Vircadia-Alpha-PR429-f6680cd.tar_7dd5a277.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR429/Vircadia-Alpha-PR429-f6680cd.tar_7dd5a277.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR429/Vircadia-Alpha-PR429-f6680cd_7dd5a277.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR429/Vircadia-Alpha-PR429-f6680cd_7dd5a277.exe

**Comment by JulianGro** [comment]
This works fine on my debian 10 server with the AMD Athlon II X4 635. But it is a headless server and I really do not want to mess with it, so I cannot test the interface.

**Comment by kasenvr** [comment]
Tested using a Windows 10 Pro computer with a Ryzen 2700X. I launched the sandbox and connected with two clients on the same computer, the server was running Opus and I spoke a few sentences into the mic and it sounded fine. The first time it got messed up but I rebooted the server and it was fine after that, unsure what caused the first hiccup.

**Pull request merged**
