### PR TITLE
Add LOD to graphic menu

### PR DESCRIPTION
**Pull request by vegaslon**
https://i.gyazo.com/6084b00b7cde1489148fc8b60e2cd80d.png

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR645/Vircadia-Alpha-PR645-b78a58c_06b0545e.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR645/Vircadia-Alpha-PR645-b78a58c.tar_06b0545e.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR645/Vircadia-Alpha-PR645-b78a58c.tar_06b0545e.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR645/Vircadia-Alpha-PR645-b78a58c_06b0545e.exe

**Comment by daleglass** [comment]
Comments during meeting: the LOD setting may not be working correctly, and exposing it may not be desirable.

**Comment by vegaslon** [comment]
Closing until such time properly talked about.

**Comment by kasenvr** [comment]
@daleglass is correct since what we can do/remain for now is let the LOD be set to max manually to prevent it from affecting anyone. So I apologize for recommending this as an interesting thing to throw in, I was going off the idea that it was/would be already enabled for people and people would need to be able to disable it somehow. However, that is not the case, though I haven't installed a fresh build in a while to confirm.

One thing that this code can be converted for might be maximum texture memory, if not a radial button group. What do you think might be more ideal for something like that? A dropdown menu would also work, potentially.

Either way, many of the boxes in the Developer -> Render menu do need to be brought over such as: shadows, ambient occlusion, etc. as those are used features that would do well to be toggleable.

**Pull request closed without merging**
