### PR TITLE
TEST PR: Build domain-server and Interface for Bluestuff metaverse

### PR DESCRIPTION
**Pull request by Misterblue**
DO NOT MERGE. This PR changes the metaverse-server URLs to point to the test metaverse at Bluestuff.org. This PR exists to build the domain-server and Interface for that metaverse for testing.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR472/Vircadia-Alpha-PR472-2729619_a1e30d24.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR472/Vircadia-Alpha-PR472-2729619.tar_a1e30d24.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR472/Vircadia-Alpha-PR472-2729619_a1e30d24.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR472/Vircadia-Alpha-PR472-2729619.tar_a1e30d24.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR472/Vircadia-Alpha-PR472-2729619_a1e30d24.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR472/Vircadia-Alpha-PR472-ca5c76b.tar_a1e30d24.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR472/Vircadia-Alpha-PR472-ca5c76b.tar_a1e30d24.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR472/Vircadia-Alpha-PR472-ca5c76b_a1e30d24.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR472/Vircadia-Alpha-PR472-ca5c76b_a1e30d24.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR472/Vircadia-Alpha-PR472-ca5c76b_a1e30d24.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR472/Vircadia-Alpha-PR472-ca5c76b.tar_a1e30d24.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR472/Vircadia-Alpha-PR472-ca5c76b_a1e30d24.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR472/Vircadia-Alpha-PR472-ca5c76b.tar_a1e30d24.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR472/Vircadia-Alpha-PR472-ca5c76b_a1e30d24.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR472/Vircadia-Alpha-PR472-ca5c76b_a1e30d24.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR472/Vircadia-Alpha-PR472-958c84e_088296ad.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR472/Vircadia-Alpha-PR472-958c84e.tar_088296ad.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR472/Vircadia-Alpha-PR472-958c84e.tar_088296ad.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR472/Vircadia-Alpha-PR472-958c84e_088296ad.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR472/Vircadia-Alpha-PR472-958c84e_088296ad.exe

**Comment by kasenvr** [comment]
Looks like this did its job! Shall we close it now? :)

**Comment by Misterblue** [comment]
This PR has served its purpose. With the move to vircadia.com, this is no longer needed.

**Pull request closed without merging**
