### PR TITLE
Also Playing with GHA

### PR DESCRIPTION
**Pull request by thoys**

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR622/Vircadia-Alpha-PR622-dbda1e9.tar_f3b546b6.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR622/Vircadia-Alpha-PR622-dbda1e9_f3b546b6.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR622/Vircadia-Alpha-PR622-dbda1e9.tar_f3b546b6.Z

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR622/Vircadia-Alpha-PR622-bb86fcd.tar_e09c167e.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR622/Vircadia-Alpha-PR622-bb86fcd.tar_e09c167e.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR622/Vircadia-Alpha-PR622-bb86fcd_e09c167e.sh

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR622/Vircadia-Alpha-PR622-fb737ac.tar_e9031f9e.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR622/Vircadia-Alpha-PR622-fb737ac.tar_e9031f9e.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR622/Vircadia-Alpha-PR622-fb737ac_e9031f9e.sh

**build (android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR622/Vircadia-Quest-Beta-PR622-fb737ac_e9031f9e.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR622/Vircadia-Beta-PR622-fb737ac_e9031f9e.apk

**Comment by thoys** [comment]
Closing this. It seems to work. @HifiExperiments you know what to do :)

**Pull request closed without merging**
