### PR TITLE
Fix models not scaling correctly when loading due to timeout.

### PR DESCRIPTION
**Pull request by kasenvr**
**Issue:** Loading a model through the Create App would cause its dimensions to be set to 1m^3. This would happen because the app would wait for the model to load before checking its dimensions and setting them, however the app had a strict timeout of 1s. So, if the model is in your cache then it would work. If the model was cachebusted or just in general new, it would not work as the loading would *likely* take more than 1 second.

**Solution:** I raised the timeout to 10 seconds and also put a message if the model gets wrongly sized due to running out of time that way the user will at least have some indication of what happened, and why, and so will developers.

**Test Plan:** Load a model entity into the world that is not cached, cachebust one if you would like. If it comes in under 10 seconds, it should be set to the correct dimensions. If it takes more than 10 seconds, it should be 1m^3.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Need a description of the problem / test plan.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR442/Vircadia-Alpha-PR442-f69b051.tar_39104483.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR442/Vircadia-Alpha-PR442-f69b051_39104483.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR442/Vircadia-Alpha-PR442-f69b051.tar_39104483.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR442/Vircadia-Alpha-PR442-f69b051_39104483.exe

**Comment by SilverfishVR** [comment]
Models come in at correct scale but if the user is in create mode and tries to rescale immediately (with gizmo) it pops back to 1x1x1.
does not happen if you deselect, and then select and rescale.

**Comment by kasenvr** [comment]
That's good feedback, I'll take a look. :)

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR442/Vircadia-Alpha-PR442-9c77dbc_3e585267.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR442/Vircadia-Alpha-PR442-9c77dbc.tar_3e585267.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR442/Vircadia-Alpha-PR442-9c77dbc_3e585267.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR442/Vircadia-Alpha-PR442-9c77dbc.tar_3e585267.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR442/Vircadia-Alpha-PR442-9c77dbc_3e585267.exe

**Comment by SilverfishVR** [comment]
Testing _PR442-9c77dbc_

It seems to all work now, no issues found 👍

**Pull request merged**
