### PR TITLE
Feature/slider app

### PR DESCRIPTION
**Pull request by kasenvr**
This is the initial PR for the slider app. This is a very early version of the app.

It can be used live at:

https://cdn.vircadia.com/assets/public/script/slider/*

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-8214249.tar_559f49ac.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-8214249_559f49ac.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-8214249.tar_559f49ac.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-8214249_559f49ac.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-8214249_559f49ac.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-053aa04_51b3018d.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-053aa04.tar_51b3018d.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-053aa04.tar_51b3018d.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-053aa04_51b3018d.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-053aa04_51b3018d.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-b6fe04b.tar_771215b6.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-b6fe04b.tar_771215b6.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-b6fe04b_771215b6.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-b6fe04b_771215b6.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-b6fe04b_771215b6.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-46276cb.tar_0d080f31.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-46276cb_0d080f31.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-46276cb.tar_0d080f31.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-46276cb_0d080f31.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-46276cb_0d080f31.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-99e7e07.tar_388da2d9.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-99e7e07.tar_388da2d9.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-99e7e07_388da2d9.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-99e7e07_388da2d9.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-99e7e07_388da2d9.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-3cf577c_31ee2d6d.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-3cf577c.tar_31ee2d6d.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-3cf577c_31ee2d6d.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-3cf577c.tar_31ee2d6d.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR541/Vircadia-Alpha-PR541-3cf577c_31ee2d6d.exe

**Comment by kasenvr** [comment]
This script should be added to the vircadia-content repo. :)

**Pull request closed without merging**
