### PR TITLE
Fix domain-server settings "Create new domain ID" dialog.

### PR DESCRIPTION
**Pull request by kasenvr**
It does what it says! Try to use that dialog successfully... try to break it by inputting illegal characters "%$#%#$%!@#", see if it breaks for you. Otherwise, should be good to go. :)

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR846/Vircadia-Alpha-PR846-ff6cdaf.tar_6232aba6.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR846/Vircadia-Alpha-PR846-ff6cdaf_6232aba6.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR846/Vircadia-Alpha-PR846-ff6cdaf.tar_6232aba6.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR846/Vircadia-Alpha-PR846-ff6cdaf_6232aba6.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR846/Vircadia-Alpha-PR846-ff6cdaf_6232aba6.exe

**Review by ctrlaltdavid — CHANGES_REQUESTED** [review]

**Review by ctrlaltdavid — APPROVED** [review]

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR846/Vircadia-Alpha-PR846-8e1837a.tar_bb35521d.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR846/Vircadia-Alpha-PR846-8e1837a.tar_bb35521d.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR846/Vircadia-Alpha-PR846-8e1837a_bb35521d.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR846/Vircadia-Alpha-PR846-8e1837a_bb35521d.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR846/Vircadia-Alpha-PR846-8e1837a_bb35521d.exe

**Comment by Aitolda** [comment]
> It does what it says! Try to use that dialog successfully... try to break it by inputting illegal characters "%$#%#$%!@#", see if it breaks for you. Otherwise, should be good to go. :)

A little more explaination might be useful.  Should it now work with those characters and it wasn't before? What exactly is the desired behavior?

**Comment by kasenvr** [comment]
> 
> 
> > It does what it says! Try to use that dialog successfully... try to break it by inputting illegal characters "%$#%#$%!@#", see if it breaks for you. Otherwise, should be good to go. :)
> 
> A little more explaination might be useful. Should it now work with those characters and it wasn't before? What exactly is the desired behavior?

It should not allow those characters but rather it should offer you an error dialog (and explain why if it got an error reason back from the server), and allow you to cancel or retry. :)

**Comment by Misterblue** [comment]
I gave this a test and it properly gave errors when the name was in errors.

A suggestion is to have text that explains what legal domain names consist of (a-z0-9+-_)

**Comment by kasenvr** [comment]
> 
> 
> I gave this a test and it properly gave errors when the name was in errors.
> 
> A suggestion is to have text that explains what legal domain names consist of (a-z0-9+-_)

True, but maybe if possible that should be included in the error message? Because that can vary based on a configuration for a metaverse server I imagine. So since I am displaying the error message directly then it'll have the most accurate information. :)

**Comment by Misterblue** [comment]
That's a good idea. I will add an issue for Iamus and have that in the next release

**Pull request merged**
