### PR TITLE
Feature/further rebranding

### PR DESCRIPTION
**Pull request by kasenvr**
This addresses the code review and QA feedback for PR #356 and completely merges it.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR427/Vircadia-Alpha-PR427-80dc597_085b9e11.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR427/Vircadia-Alpha-PR427-80dc597.tar_085b9e11.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR427/Vircadia-Alpha-PR427-80dc597.tar_085b9e11.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR427/Vircadia-Alpha-PR427-80dc597_085b9e11.exe

**Comment by ctrlaltdavid** [comment]
Tested Windows installer. Issues:
- Vircadia setup dialog still has the Kasen logo. See screen snap.
- Sandbox desktop icon still is the Kasen logo (but Interface desktop icon is a Vircadia one). See screen snap.
- Server Console icon in Windows system tray is still Kasen logo.
- In-world login dialog is broken. See screen snap. Repro: While in a domain, File > Logout, then File > Login.

Vircadia setup dialog logo
Desktop icons
In-world login dialog

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR427/Vircadia-Alpha-PR427-b1eda4b_c55f365a.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR427/Vircadia-Alpha-PR427-b1eda4b.tar_c55f365a.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR427/Vircadia-Alpha-PR427-b1eda4b.tar_c55f365a.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR427/Vircadia-Alpha-PR427-b1eda4b_c55f365a.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR427/Vircadia-Alpha-PR427-b1eda4b_c55f365a.exe

**Comment by ctrlaltdavid** [comment]
Test installed Windows build. 4 x issues noted above have been fixed. Seems to be working OK in general.

**Pull request merged**
