### PR TITLE
Feature: Create Material even without a URL.

### PR DESCRIPTION
**Pull request by AleziaKurdis**
This enhancement changes the behavior when a Material Entity is created using the Create App.
Previously, if we left the URL null, no entity was created.
With this fix, if we left the URL null, then the entity is created with "materialData" already set in materialURL (ready to use Material Data).

This include a revisited tooltip for materialURL (that was obscure).
"The URL to an external JSON file or "materialData".  Append "?<materialName>" to select a single material if multiple are defined."

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR703/Vircadia-Alpha-PR703-a05aa4c.tar_180742f7.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR703/Vircadia-Alpha-PR703-a05aa4c.tar_180742f7.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR703/Vircadia-Alpha-PR703-a05aa4c_180742f7.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR703/Vircadia-Alpha-PR703-a05aa4c_180742f7.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR703/Vircadia-Alpha-PR703-a05aa4c_180742f7.exe

**Review by kasenvr — APPROVED** [review]

**Comment by SilverfishVR** [comment]
It seems, a "Material Data" material entity with empty material data is invisible, so I would suggest at least adding albedo {1, 1, 1}.
unless #390 is implemented.

**Comment by Aitolda** [comment]
I created a material entity and skipped adding anything to the URL line.  The result was a visibly white material entity and seemed to work as expected.  One thought though, perhaps the URL box might say something like [Optional] so a new user knows they can skip it.

**Comment by kasenvr** [comment]
Assuming Silverfish also gave this a test, then it looks safe enough to consider QA approved. :)

**Comment by AleziaKurdis** [comment]
image

**Comment by Aitolda** [comment]
Nice! Perfect.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR703/Vircadia-Alpha-PR703-c48d273.tar_ec4d5590.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR703/Vircadia-Alpha-PR703-c48d273_ec4d5590.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR703/Vircadia-Alpha-PR703-c48d273.tar_ec4d5590.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR703/Vircadia-Alpha-PR703-c48d273_ec4d5590.exe

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR703/Vircadia-Alpha-PR703-c48d273_ec4d5590.dmg

**Comment by AleziaKurdis** [comment]
image

**Comment by AleziaKurdis** [comment]
image

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR703/Vircadia-Alpha-PR703-084f5d7_6ca17633.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR703/Vircadia-Alpha-PR703-084f5d7.tar_6ca17633.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR703/Vircadia-Alpha-PR703-084f5d7.tar_6ca17633.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR703/Vircadia-Alpha-PR703-084f5d7_6ca17633.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR703/Vircadia-Alpha-PR703-084f5d7_6ca17633.exe

**Pull request merged**
