### PR TITLE
Fix pick rays not intersecting glTF models

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
This PR fixes the problem of pick rays not intersecting many glTF entities.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR699/Vircadia-Alpha-PR699-c31f644_84cb3b25.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR699/Vircadia-Alpha-PR699-c31f644_84cb3b25.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR699/Vircadia-Alpha-PR699-c31f644.tar_84cb3b25.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR699/Vircadia-Alpha-PR699-c31f644.tar_84cb3b25.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR699/Vircadia-Alpha-PR699-c31f644_84cb3b25.exe

**Review by HifiExperiments — APPROVED** [review]
seems fine to me!  I can’t imagine why adding this back would break anything else

I wonder if this fixes the model instancing thing...I’ll merge in master once this is merged

**Comment by ctrlaltdavid** [comment]
The FBX reader has equivalent code.

**Comment by Aitolda** [comment]
Seems to be working as intended.  Checked with binary and non-binary, embedded and non-embedded.

**Pull request merged**
