### PR TITLE
New URL for default Particle and Image resource 

### PR DESCRIPTION
**Pull request by AleziaKurdis**
This PR replace the default URL for Image and Particle entities
to use local resources.
the resource as been added to a "default" folder in interface/resources
This folder is also exposed in the installer as we do for fonts. 

I have tested the URL,
But I have not tested the installation (if the new resource folder is correctly installed)
(sorry, I'm not familiar with compiling and building)

This need to be tested on all OS to see if those local URL really work everywhere.

### CODE REVIEW

**Comment by AleziaKurdis** [comment]
This PR addresses the issues:
#534 and #601

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR604/Vircadia-Alpha-PR604-8295e42_e2ee9c98.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR604/Vircadia-Alpha-PR604-8295e42.tar_e2ee9c98.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR604/Vircadia-Alpha-PR604-8295e42.tar_e2ee9c98.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR604/Vircadia-Alpha-PR604-8295e42_e2ee9c98.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR604/Vircadia-Alpha-PR604-8295e42_e2ee9c98.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR604/Vircadia-Alpha-PR604-f5807fa_440db34a.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR604/Vircadia-Alpha-PR604-f5807fa.tar_440db34a.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR604/Vircadia-Alpha-PR604-f5807fa_440db34a.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR604/Vircadia-Alpha-PR604-f5807fa.tar_440db34a.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR604/Vircadia-Alpha-PR604-f5807fa_440db34a.exe

**Comment by kasenvr** [comment]
image
Looks good to me, only thing is that is how the texture preview shows up in the Create App. I assume that's because there's no good way to access resources other than through Interface's internal systems?

OS Name	Microsoft Windows 10 Pro
Version	10.0.18363 Build 18363

**Comment by kasenvr** [comment]
We need an OSX and Linux tester next. :)

**Comment by AleziaKurdis** [comment]
> Looks good to me, only thing is that is how the texture preview shows up in the Create App. I assume that's because there's no good way to access resources other than through Interface's internal systems?

I found that bug too, exploring the code for that other PR "#606 Change colorSpread color-picker and other small fixes"
I fixed it on the fly. But it gets part of PR #606.
So the fixe for that is in the stack. 
There was a condition for "atp:/," because it's unable to read for a preview. I added it for "file:/," since it is also unable to read using such a 'relative' path. So a placeholder is displayed.

**Comment by JulianGro** [comment]
1Auswahl_726
Works fine on Linux Mint 19.3. Only the preview doesn't work, like Kalila reported already.

**Comment by kasenvr** [comment]
Awesomeness, if the fix is there then I'm sure it'll be fine. :)

**Comment by kasenvr** [comment]
Worked on OSX too, so all QA tested.

**Comment by JulianGro** [comment]
> It would probably be better to put the images on the Vircadia CDN rather than rely on a user's Interface having the files at specific location. Though your Interface may have the image files when you create the entities, someone else's (old or future) Interface may not have the images files and so they won't see the images. @kasenvr
> 
> If it really is wanted to have the image files locally, it would probably be better to put them in the already existing \interface\resources\images directory and in the script use ...
> 
> ```
> var DEFAULT_IMAGE = "file:///~/images/default_image.jpg";
> ```
> 
> and similarly for `default_particle.png`.

Personally I like having the resources in the interface rather than the cdn.
Currently we have much more control over the interface source than of the cdn and I don't really see why people would need to download something externally when it is a standard component that is used by the interface.

**Comment by daleglass** [comment]
Files uploaded to:

http://eu-central-1.linodeobjects.com/vircadia-assets/interface/default/default_image.jpg
http://eu-central-1.linodeobjects.com/vircadia-assets/interface/default/default_particle.png

**Comment by ctrlaltdavid** [comment]
A problem with using `file:///` URLs as the default is that it indicates to users that local files can be used for textures; they're liable to be surprised if they select a different local file on their PC and other people cannot see it.

**Comment by kasenvr** [comment]
I see that in the future with things like IPFS this can be accomplished for both cases.

**Comment by AleziaKurdis** [comment]
> A problem with using `file:///` URLs as the default is that it indicates to users that local files can be used for textures; they're liable to be surprised if they select a different local file on their PC and other people cannot see it.

It was initially my concern too by using such local url.

**Comment by AleziaKurdis** [comment]
Rollbacked this. 
And changed the URLs for their new storage locations.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR604/Vircadia-Alpha-PR604-aeab026.tar_e1d956b2.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR604/Vircadia-Alpha-PR604-aeab026.tar_e1d956b2.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR604/Vircadia-Alpha-PR604-aeab026_e1d956b2.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR604/Vircadia-Alpha-PR604-aeab026_e1d956b2.exe

**Pull request merged**
