### PR TITLE
Revert "Revert "Split Local and owned Avatar Entity scripts into their own ScriptEngine""

### PR DESCRIPTION
**Pull request by HifiExperiments**
take 2

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR871/Vircadia-Alpha-PR871-dd6a9f5.tar_b6744588.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR871/Vircadia-Alpha-PR871-dd6a9f5.tar_b6744588.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR871/Vircadia-Alpha-PR871-dd6a9f5_b6744588.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR871/Vircadia-Alpha-PR871-dd6a9f5_b6744588.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR871/Vircadia-Alpha-PR871-dd6a9f5_b6744588.exe

**Review by ctrlaltdavid — APPROVED** [review]

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR871/Vircadia-Alpha-PR871-dd6a9f5_b6744588.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR871/Vircadia-Alpha-PR871-dd6a9f5.tar_b6744588.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR871/Vircadia-Alpha-PR871-dd6a9f5.tar_b6744588.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR871/Vircadia-Alpha-PR871-dd6a9f5_b6744588.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR871/Vircadia-Alpha-PR871-dd6a9f5_b6744588.exe

**Comment by kasenvr** [comment]
Looks like it's working pretty alright to me. :)

**Comment by Aitolda** [comment]
Domain loading doesn't seem to be a problem anymore.  I went to 10+ domains that weren't cached and everyone loaded as expected.  If anything, it's working better than in a very long time.  Revisiting yields the same result.

**Pull request merged**
