### PR TITLE
Add support for serverless domains via HTTP/HTTPS

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
- Add support for serverless domains via HTTP/HTTPS.
- Fix missing "no connection" dialog for invalid serverless domains.
- Add support for serverless domains via FILE and HTTP/HTTPS in the --url command line parameter.

Issue: https://github.com/kasenvr/project-athena/issues/106

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Testing

1. Check that going to the installed serverless tutorial still works, i.e., file:///~/serverless/tutorial.json.

2. Host a copy of tutorial.json on the Web and check that you can go to the serverless tutorial via:
- http
- https

3. Check that the serverless tutorial is included in the Goto history (i.e., you can go back to it and go forward to it).

4. Check that Interface starts at the serverless tutorial if that was your current place when you last exited Interface.

5. Check that you can specify FILE and HTTP/HTTPS serverless tutorials as the start-up domain using the `--url` command line parameter.

6. Check that if Interface is already running, using the `--url` command line parameter with FILE and HTTP/HTTPS serverless tutorial causes the already running Interface to go to those tutorials.

7. Check that trying to go to invalid file and http/https URLs behaves properly: not connected state with "(NOT CONNECTED)" in the title bar; "No Connection" dialog box after a short while; Goto app's "go back" button takes you back to the previous location.

8. Check that other  Goto types still work in the Goto dialog, e.g.:
- Going to a position and orientation in the current domain.
- Going to another domain via place name.
- Going to another domain via Web domain name.
- Going to another domain via IP address.
- Going to localhost.
- Going to a person.
- Going to a domain using --url in the command line.

**Comment by MarcusLlewellyn** [comment]
Unofficial PR build here: [ProjectAthena-Alpha-PR160-c5716c5.exe](https://drive.google.com/file/d/1XFtjY4FdJavtq8911lIrM9RnqFtmeXeG/view?usp=sharing)

**Comment by Aitolda** [comment]
Confirmed. Working as expected after following testing intstructions.

**Comment by kasenvr** [comment]
Appears to be working as expected. :)

**Pull request merged**
