### PR TITLE
Fix for Issue 696. Create App - List refresh on updating image URL

### PR DESCRIPTION
**Pull request by AleziaKurdis**
This fixes a refresh of the FILE value in the Create App Entity list when updating the imageURL of an Image Entity.
(It was missing in the condition that checks to add to the refresh of the list.)

This solves the issue #696.

### CODE REVIEW

**Comment by JulianGro** [comment]
Just gave it a quick test, and it does fix the issue of the image filename not updating.
It doesn't fix the entity list jumping a step back, but I will open a separate issue for that.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR701/Vircadia-Alpha-PR701-f615bfa_6337e848.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR701/Vircadia-Alpha-PR701-f615bfa.tar_6337e848.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR701/Vircadia-Alpha-PR701-f615bfa.tar_6337e848.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR701/Vircadia-Alpha-PR701-f615bfa_6337e848.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR701/Vircadia-Alpha-PR701-f615bfa_6337e848.exe

**Comment by Aitolda** [comment]
Entity list refreshes as intended.

**Review by kasenvr — APPROVED** [review]
Looks fine to me. :) (CR, not QA)

**Pull request merged**
