### PR TITLE
Update shortcut names to include "Vircadia"

### PR DESCRIPTION
**Pull request by kasenvr**
You have to package and install a full build to test this.

Use this build to test: http://cdn.vircadia.com/dist/pr-builds/Vircadia-Alpha-2020.3.0-Demeter.exe

In testing, you will want to uninstall Vircadia first. You will then also want to clear out any and all start menu shortcuts that may remain as old names from the Start Menu shortcuts as they will not be handled by the installer/uninstaller. Then install Vircadia, ensure shortcuts are correct, then uninstall to ensure they are also removed.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-5f12b8b_bb3ea101.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-5f12b8b.tar_bb3ea101.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-5f12b8b.tar_bb3ea101.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-5f12b8b_bb3ea101.exe

**Review by daleglass — APPROVED** [review]

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-105be16_bb3ea101.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-105be16.tar_bb3ea101.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-105be16_bb3ea101.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-105be16.tar_bb3ea101.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-105be16_bb3ea101.exe

**Review by ctrlaltdavid — APPROVED** [review]

**Comment by kasenvr** [comment]
I need to properly test this before merging, to make sure there are no adverse effects.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-e672598.tar_bb3ea101.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-e672598.tar_bb3ea101.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-e672598_bb3ea101.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-e672598_bb3ea101.dmg

**Comment by kasenvr** [comment]
Tested and fixed one issue, appears to be alright though.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-0969743.tar_11d847b7.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-0969743_11d847b7.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-0969743.tar_11d847b7.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-0969743_11d847b7.dmg

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-8c0e34c_aa20fbb0.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-8c0e34c.tar_aa20fbb0.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-8c0e34c_aa20fbb0.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-8c0e34c.tar_aa20fbb0.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-8c0e34c_aa20fbb0.exe

**Review by ctrlaltdavid — APPROVED** [review]

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-d75fc4d_5e43b3a5.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-d75fc4d.tar_5e43b3a5.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-d75fc4d_5e43b3a5.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-d75fc4d.tar_5e43b3a5.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-d75fc4d_5e43b3a5.exe

**Comment by kasenvr** [comment]
Appears to work alright for Release & PR.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-81a0bd7_6e7e7f5c.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-81a0bd7.tar_6e7e7f5c.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-81a0bd7.tar_6e7e7f5c.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-81a0bd7_6e7e7f5c.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR651/Vircadia-Alpha-PR651-81a0bd7_6e7e7f5c.exe

**Comment by kasenvr** [comment]
After uninstalling and manually deleting the start menu shortcuts, it installed correctly with the two shortcuts being "Vircadia" (for the Interface) and "Vircadia Sandbox" as expected.

**Comment by kasenvr** [comment]
QA Approved unless someone wants to take a stab at testing this as well!

**Comment by ctrlaltdavid** [comment]
Tested on Windows using the installer from the first comment:
- Installed after uninstalling 2020.3.0.
- Installed over the top of 2020.3.0.

Both worked. The only difference was that the current release creates only two Start menu items: "Uninstall" and "Vircadia", whereas the PR installer creates three: "Uninstall", "Vircadia", "Vircadia Sandbox".

**Pull request merged**
