### PR TITLE
Rebranding stuff

### LINKED ISSUE #332: Fix High Fidelity logos in image files
At least one of the image files in \interface\resources\images still includes the High Fidelity logo: steam-min-spec-failed.png. Fix this and check for other occurrences.

### LINKED ISSUE #345: Installer still has "Project Athena" and related
The installer dialog from PR builds has:
- "Project Athena" in the title bar.
- Project Athena logo.
- "Project Athena …" in various dialog text elements.
- "Proiect Athena" in license displayed.
- Installs in C:\Program Files\Project Athena - PRnnn

### PR DESCRIPTION
**Pull request by JulianGro**
This rebrands everything with the term "Project Athena" in it, except the parts of the pkg-scripts I didn't want to mess with. If someone wants to provide changes to the pkg-scripts, just request a change, write under this, make a pull request to my branch, or just make another pull request to master.
This also replaces a bunch of the image resources from Project Athena and HiFi with Vircadia ones. The old resources have been deleted.
Some directory names are also changed, which makes it not use the old interface config folders. I guess this should have been done sooner rather than later.

Closes #345

### CODE REVIEW

**Comment by kasenvr** [comment]
There are three other branding PRs waiting, once all three of those are merged then we'll see the difference in what you merged and move forward with that. :) Thanks for your hard work!

**Comment by kasenvr** [comment]
Alrighty, so all the relevant PRs have been merged, when you have a chance, can you resolve conflicts to master and then see what's left? :)

**Comment by JulianGro** [comment]
@kasenvr conflicts are resolved, and PR is open for review

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR384/Vircadia-Alpha-PR384-c588e3c.tar_170c78e2.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR384/Vircadia-Alpha-PR384-c588e3c_170c78e2.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR384/Vircadia-Alpha-PR384-c588e3c.tar_170c78e2.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR384/Vircadia-Alpha-PR384-c588e3c_170c78e2.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR384/Vircadia-Alpha-PR384-c588e3c_170c78e2.exe

**Comment by kasenvr** [comment]
For the files: 
`interface/resources/images/about-vircadia.png`
and
`interface/resources/images/vircadia-logo.svg`

You may want to not alter those as they were already handled in the last merge. It also changes them to an icon format instead of the full worded logo. In some places that might be an interesting direction to take it but currently the QML sets the dimensions for the full size logo.

image

**Comment by JulianGro** [comment]
@kasenvr should be fixed now. The about-vircadia.png is edited, because it leaves some space around it, like the about-projectathena.png did before it.
The banner for the login dialog should not be called "logo" since that is already used for the window icon, so I just renamed it as per last commit.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR384/Vircadia-Alpha-PR384-4c50f96.tar_18318fdf.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR384/Vircadia-Alpha-PR384-4c50f96.tar_18318fdf.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR384/Vircadia-Alpha-PR384-4c50f96_18318fdf.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR384/Vircadia-Alpha-PR384-4c50f96_18318fdf.exe

**Pull request merged**
