### PR TITLE
Replace set-env in PR GHA

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Code from commit 4c536f4 by HifiExperiments.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR872/Vircadia-Alpha-PR872-echo e3d590b11dd899e15f1d54d86939695bac01b2d2 | cut -c1-7.tar_57729e3c.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR872/Vircadia-Alpha-PR872-echo e3d590b11dd899e15f1d54d86939695bac01b2d2 | cut -c1-7.tar_57729e3c.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR872/Vircadia-Alpha-PR872-echo e3d590b11dd899e15f1d54d86939695bac01b2d2 | cut -c1-7_57729e3c.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR872/Vircadia-Alpha-PR872-echo e3d590b11dd899e15f1d54d86939695bac01b2d2 | cut -c1-7_57729e3c.dmg

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR872/Vircadia-Alpha-PR872-{{github_sha_sort}}_c2990263.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR872/Vircadia-Alpha-PR872-{{github_sha_sort}}.tar_c2990263.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR872/Vircadia-Alpha-PR872-{{github_sha_sort}}.tar_c2990263.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR872/Vircadia-Alpha-PR872-{{github_sha_sort}}_c2990263.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR872/Vircadia-Alpha-PR872-{{github_sha_sort}}_c2990263.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR872/Vircadia-Alpha-PR872-d600579_e8520bec.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR872/Vircadia-Alpha-PR872-d600579_e8520bec.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR872/Vircadia-Alpha-PR872-d600579.tar_e8520bec.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR872/Vircadia-Alpha-PR872-d600579.tar_e8520bec.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR872/Vircadia-Alpha-PR872-d600579_e8520bec.exe

**Review by HifiExperiments — COMMENTED** [review]
do we need these changes in the master_builds file too?

**Pull request merged**
