### PR TITLE
Disable Certified Entity Auto Deletion

### PR DESCRIPTION
**Pull request by kasenvr**
I've neutered the auto-deletion for entities that are certified, however I kept intact the verification checks.

What should be done next: move certified checks into their own files. Certified checks will get routed through the metaverse API that you are connected to, it is up to that API if it cares or not. The next thing to do after that is to allow you to change the certified URL by setting so you can have a certifying authority that is not routed through your metaverse API provider.

**To test:**

Launch your sandbox and try to rez a certified entity that does not allow copies multiple times. To verify that it is working, you can read in your server-console's assignment client logs where the check is happening, it will have a line along the lines of "No action will be taken to delete the entity."

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR438/Vircadia-Alpha-PR438-4f35f15_49f72f0c.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR438/Vircadia-Alpha-PR438-4f35f15.tar_49f72f0c.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR438/Vircadia-Alpha-PR438-4f35f15.tar_49f72f0c.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR438/Vircadia-Alpha-PR438-4f35f15_49f72f0c.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR438/Vircadia-Alpha-PR438-4f35f15_49f72f0c.exe

**Comment by vegaslon** [comment]
I agree, think it would be wiser for people just to accept that highfidelity in this form is gone and that any content they licensed they need to try to contact the seller for a different license.

**Comment by kasenvr** [comment]
I must be clear though that this is not disabling certification checking, this is simply stopping the unapproved deletion of entities by the system without option.

The license that they got was with High Fidelity Inc. for High Fidelity's marketplace as well, we don't own the marketplace so there's not much to say for that. If someone wants to start a new marketplace and allow for transfer of items and an honoring of that previous license, that might be cool, but again the system in its vanilla form probably should...

1. not delete entities against the admin/user's will.
2. offer the option to enable such auto-deletion for your domain if you wish it based on what the verification check finds.
3. set your own verification servers.

This PR accomplishes step 1. Step 2 and step 3 should be completed later. The purpose for step 1 being completed now is because it is considered an issue for many domain owners currently that have their owned assets being nuked by the systems for an unsupported (it works, but is currently on life support as far as we know) marketplace.

**Comment by vegaslon** [comment]
You are saying that the domain operator has more rights then the creator of the content with this pr and licensing be completely nulled officially in vircadia.

**Comment by kasenvr** [comment]
> 
> 
> You are saying that the domain operator has more rights then the creator of the content with this pr and licensing be completely nulled officially in vircadia.

No, I am saying this is the equivalent of this:

Firefox detects that you are not licensed to download this unwatermarked stock photo, Firefox deletes the file off your system after downloading it, you never get a choice.

Firefox should really have no opinion on this, it can notify you if a website is certified for example, if it is what it says it is, but you can choose to override that. It's up to you to respect a license.

Auto deletion functions != license, has nothing to do with a license and legal agreements.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR438/Vircadia-Alpha-PR438-022c3b4_f6214d46.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR438/Vircadia-Alpha-PR438-022c3b4.tar_f6214d46.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR438/Vircadia-Alpha-PR438-022c3b4_f6214d46.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR438/Vircadia-Alpha-PR438-022c3b4.tar_f6214d46.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR438/Vircadia-Alpha-PR438-022c3b4_f6214d46.exe

**Comment by vegaslon** [comment]
your choice of example of what you mean is poor, you can block firefox from letting people save your images, and copying your text off your website.

**Comment by kasenvr** [comment]
> your choice of example of what you mean is poor, you can block firefox from letting people save your images, and copying your text off your website.

Yes, this is true. Using various JavaScript and CSS techniques, but you cannot outright control the browser to tell it that it cannot. I am saying that an uncontrolled auto-delete function for an uncontrolled and unrelated system that is hardcoded into the C++ at this moment in time has been affecting many users for a while now. :)

And to be more specific, this deletion happens on the server. So it's like telling a web server owner that they cannot decide how to host or allow what content, it has historically always been up to them. There are no open source or mainstream systems that force content based on license without a choice as far as I know.

I agree though that certification is important, it's something also important to me to help authenticity and markets, which is why I want the system to remain in place but have it handle things gracefully and so that there is also an option for how to handle it. Forcing the decision will not help achieve the desired result in the long run is what I have noticed. 

People will respect license and business models will evolve to fit, but regardless auto-delete functions hardcoded with no option cause distress to the users and the very creators of those very same items as has been noted in a great many reports to the issue recently and over the years. So I'm hoping to help fix that, step by step, and help us get a certification system that works even better in the wider market model. :)

**Comment by vegaslon** [comment]
perhaps this pr also needs to disable the marketplace app as well. people that have existing content put out would continue to have it but would be unable to create more.

**Comment by kasenvr** [comment]
Dave_K confirmed this is working as intended for him.

**Pull request merged**
