### PR TITLE
Quiet warning for unused blendshapeCoefficients property

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Testing

Using the current Vircadia release, not the occurrence of many program log entries:
```
WARNING] [default] Could not evaluate blendshapeCoefficients property value: QJsonDocument()
```

These warnings arise for Model entities that don't have their `blendshapeCoefficients` property value set.

Using the PR build on the same domain, these warning messages should not be logged.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR705/Vircadia-Alpha-PR705-23da200.tar_432090e2.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR705/Vircadia-Alpha-PR705-23da200_432090e2.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR705/Vircadia-Alpha-PR705-23da200.tar_432090e2.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR705/Vircadia-Alpha-PR705-23da200_432090e2.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR705/Vircadia-Alpha-PR705-23da200_432090e2.exe

**Review by HifiExperiments — APPROVED** [review]

**Comment by Aitolda** [comment]
I'm not sure I'm 100% on how to test this.

**Comment by kasenvr** [comment]
> 
> 
> I'm not sure I'm 100% on how to test this.

Confirm that this does show up often on the main release or master, then when you run this PR you'll notice that this will no longer occur.

**Comment by Aitolda** [comment]
> > I'm not sure I'm 100% on how to test this.
> 
> Confirm that this does show up often on the main release or master, then when you run this PR you'll notice that this will no longer occur.

So this will happen no matter what avatar is used?  Assuming we actually are talking about avatars, as I know we recently added blendshapes to models.

**Comment by ctrlaltdavid** [comment]
The problem occurs for FBX and glTF Model entities that don't have blendshapes. (It would also occur for avatars without blendshapes but this is an unlikely situation.)
If you add an entity to your domain, you'll see the message logged in current releases but not this PR release.

**Comment by Aitolda** [comment]
Seems to be working as expected.

**Pull request merged**
