### PR TITLE
Update Primary CMakeLists project name to Athena

### PR DESCRIPTION
**Pull request by MarcusLlewellyn**
Having a "hifi.sln" file feels wrong. Let's fix that.

### CODE REVIEW

**Comment by kasenvr** [comment]
Is that the only place it shows up in, I wonder?

**Comment by MarcusLlewellyn** [comment]
There are like 11000 uses of the string "hifi" all over the codebase. But this one is one of the most front-facing, and we gotta start somewhere. ;)

**Comment by kasenvr** [comment]
Oh I 100% agree, I just meant if there are any other references towards that that could break it.

**Comment by MarcusLlewellyn** [comment]
It really doesn't affect anything other than the name of the project.

**Comment by thoys** [comment]
the short name could be "athena"  instead of "hifi"

**Comment by thoys** [comment]
ah you already did it, great. did someone test this?

**Pull request merged**
