### PR TITLE
Re-enable and update code signing in the NSIS template.

### PR DESCRIPTION
**Pull request by MarcusLlewellyn**

### CODE REVIEW

**Comment by MarcusLlewellyn** [comment]
Unofficial PR build for Windows is available here: [ProjectAthena-Alpha-PR303-35da672.exe](https://cdn.vircadia.com/dist/pr-builds/ProjectAthena-Alpha-PR303-35da672.exe)

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR303/ProjectAthena-Alpha-PR303-49c2f00_4eba94b4.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR303/ProjectAthena-Alpha-PR303-49c2f00.tar_4eba94b4.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR303/ProjectAthena-Alpha-PR303-49c2f00_4eba94b4.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR303/ProjectAthena-Alpha-PR303-49c2f00.tar_4eba94b4.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR303/ProjectAthena-Alpha-PR303-49c2f00_4eba94b4.exe

**Comment by ctrlaltdavid** [comment]
From Marcus: "That block is intended to sign the uninstaller that is then packaged within the actual installer. So, to test you need to install and then uninstall. The uninstaller requires elevated privileges, so the typical "This thing wants to run" dialog pops up. If the publisher is unknown, then the uninstaller was not signed."

I test installed and uninstalled this PR and PR311 build, both on Windows …
- This PR: Installing gets User Account Control “are you sure” dialog with unknown publisher. Uninstalling reports unknown publisher.
- PR311: Installing gets “Windows protected your PC” with unknown publisher. Uninstalling reports unknown publisher.

**Comment by kasenvr** [comment]
I cannot generate an installer in the first place to confirm this is working as of yet.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR303/Vircadia-Alpha-PR303-22cf4ae.tar_db13ea76.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR303/Vircadia-Alpha-PR303-22cf4ae.tar_db13ea76.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR303/Vircadia-Alpha-PR303-22cf4ae_db13ea76.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR303/Vircadia-Alpha-PR303-22cf4ae_db13ea76.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR303/Vircadia-Alpha-PR303-22cf4ae_db13ea76.exe

**Comment by kasenvr** [comment]
Works, although the final product does not get signed for some reason, I had to sign it manually, but all of the executables within were signed so good enough...

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR303/Vircadia-Alpha-PR303-d2db33a.tar_74819256.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR303/Vircadia-Alpha-PR303-d2db33a.tar_74819256.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR303/Vircadia-Alpha-PR303-d2db33a_74819256.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR303/Vircadia-Alpha-PR303-d2db33a_74819256.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR303/Vircadia-Alpha-PR303-d2db33a_74819256.exe

**Pull request merged**
