### PR TITLE
Enable automatic avatar and audio mixer threading defaults

### PR DESCRIPTION
**Pull request by kasenvr**
Test Plan:

Start a fresh domain-server on your computer that triggers the first time setup wizard, run through it, but the last page will be these new settings. It will be disabled by default if you pass through it, but if you check the box, it will activate the values for automatic threading.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-1213742_1ea78c6a.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-1213742_1ea78c6a.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-1213742.tar_1ea78c6a.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-1213742.tar_1ea78c6a.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-1213742_1ea78c6a.exe

**Comment by kasenvr** [comment]
First test was today... had to switch to automatic threading when the audio mixer started to lose itself. Though, the server had been up some time so the failure could have been due to a memory leak potentially if it was present.

Anyway, under load I switched it and the server rebooted, it resulted in an immediate fix for the issue.

**Comment by ctrlaltdavid** [comment]
Should test on a low-end Sandbox to see what happens with and without this change, to check the effect of this change.

**Comment by JulianGro** [comment]
I feel like we might want to either have this setting disabled on sandboxes as oppose to dedicated servers and/or have a standard slot limitation for sandboxes. Because we probably just don't want it eating up all the resources.

**Comment by kasenvr** [comment]
That would be complicated to handle. However, if this is handled https://github.com/kasenvr/project-athena/issues/646 then this becomes far less of an issue. Especially considering that the Sandbox is no longer installed automatically on Windows. This means that essentially it's not something that the user is unaware of, so even if it does start eating up resources (which would require lots of attendees), they would know of its presence and would know pretty precisely that it's the sandbox causing such a thing.

However, it could still be the case that they can be running an Interface with a Sandbox and think that the Interface is just being more demanding. So... perhaps this is mergeable once an onboarding option is given to decide.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-4139813_58bbab6b.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-4139813.tar_58bbab6b.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-4139813.tar_58bbab6b.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-4139813_58bbab6b.exe

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-4139813_58bbab6b.dmg

**Comment by kasenvr** [comment]
https://github.com/kasenvr/project-athena/pull/465 should be merged before merging this.

**Comment by kasenvr** [comment]
I made the ability to toggle this as part of the onboarding wizard with it off by default, so it reminds people on first install but is clear about what it does and to leave it off if they are not sure.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-07c4b68_a513bba8.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-07c4b68.tar_a513bba8.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-07c4b68.tar_a513bba8.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-07c4b68_a513bba8.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-07c4b68_a513bba8.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-e05881d_40219e6f.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-e05881d.tar_40219e6f.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-e05881d_40219e6f.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-e05881d.tar_40219e6f.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-e05881d_40219e6f.exe

**Review by ctrlaltdavid — APPROVED** [review]

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-96b8be8.tar_5e653192.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-96b8be8.tar_5e653192.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-96b8be8_5e653192.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-96b8be8_5e653192.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-96b8be8_5e653192.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-afb4098_ba67cc82.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-afb4098_ba67cc82.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-afb4098.tar_ba67cc82.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-afb4098.tar_ba67cc82.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR546/Vircadia-Alpha-PR546-afb4098_ba67cc82.exe

**Comment by SilverfishVR** [comment]
tested PR546-afb4098_ba67cc82.exe
enabling the option at the end of the wizard made the server start up with audio and avatar mixer threads set to "auto" as expected so it looks good 👍

**Pull request merged**
