### PR TITLE
Workaround: Add Valve Index to calibratable devices

### PR DESCRIPTION
**Pull request by JulianGro**
This enables the calibration for Vive Trackers on the Valve Index. I tested this on Debian Testing:
https://data.moto9000.moe/vircadia/%23808/tracker.webm
This should be done different as most HMDs can be used via OpenVR and could also be used with Vive Trackers because of that.

### CODE REVIEW

**Review by ctrlaltdavid — COMMENTED** [review]
Looking good.

A slightly tidier, more maintainable implementation could be to declare an array of valid HMD names and check whether the `box.textAt(box.currentIndex)` value is in it.

Add a property to the top level `Item`...
```
property var openVRDevices: ["HTC Vive", "Valve Index", "Valve HMD", "Valve"]
```

Change the first test to read...
```
if (openVRDevices.indexOf(box.textAt(box.currentIndex)) !== -1) {
```

And similarly for the second `if(0)`.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR808/Vircadia-Alpha-PR808-cbdc9da_2b38c07a.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR808/Vircadia-Alpha-PR808-cbdc9da.tar_2b38c07a.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR808/Vircadia-Alpha-PR808-cbdc9da_2b38c07a.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR808/Vircadia-Alpha-PR808-cbdc9da.tar_2b38c07a.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR808/Vircadia-Alpha-PR808-cbdc9da_2b38c07a.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR808/Vircadia-Alpha-PR808-8aeb2bd.tar_1a3f97bd.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR808/Vircadia-Alpha-PR808-8aeb2bd.tar_1a3f97bd.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR808/Vircadia-Alpha-PR808-8aeb2bd_1a3f97bd.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR808/Vircadia-Alpha-PR808-8aeb2bd_1a3f97bd.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR808/Vircadia-Alpha-PR808-8aeb2bd_1a3f97bd.exe

**Review by ctrlaltdavid — APPROVED** [review]

**Review by daleglass — APPROVED** [review]

**Comment by kasenvr** [comment]
I'll give this a test on Windows w/ my Index + Vive Trackers.

**Review by kasenvr — APPROVED** [review]
Worked good for me. Although one trick is that it has motion smoothing on automatically this time, wonder where that's coming from or if it's a script... we will probably want to find out where that comes from and offer a proper toggle in that same menu.

**Comment by kasenvr** [comment]
Also get two warnings when going to the "Calibration" tab in Desktop and with SteamVR running...

```
[10/13 19:22:49] [WARNING] [default] qrc:/qml/hifi/tablet/tabletWindows/TabletPreferencesDialog.qml:22: TypeError: Cannot read property 'height' of null
[10/13 19:22:49] [WARNING] [default] qrc:/qml/hifi/tablet/tabletWindows/TabletPreferencesDialog.qml:21: TypeError: Cannot read property 'width' of null
```

**Pull request merged**
