### PR TITLE
Add option to enable/disable Vive Pro Eye eye tracking

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Adds a "use eye tracking" option to the Vive settings, that enables and disables eye tracking.

Also tidies up some dialog layout issues:
- Tweaks some text.
- Makes checkboxes square rather than round.
- Fixes position of recommended puck placement diagram.

Includes in the build package the Vive developer guidelines that prompted the need for the option.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Testing

With a Vive Eye Pro:
- Settings > Controls... > Calibration > Use eye tracking (if available) option defaults to off.
- Vive Pro Eye eye-tracking doesn't work if the option is disabled.
- Vive Pro Eye eye-tracking works if the option is enabled.
- The option setting is remembered between program runs.
- The Vive HMD and controllers work both with eye tracking enabled and eye tracking disabled.

With an ordinarly Vive:
- The Vive HMD and controllers work both with eye tracking enabled and eye tracking disabled. (I.e., the option has no effect.)

General:
- The "Privacy Statement" link after the eye tracking option opens the Vircadia privacy statement Web site page OK in both desktop mode and HMD mode. (TODO: Update with the correct URL.)

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR484/Vircadia-Alpha-PR484-ecbab2f_06010dbc.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR484/Vircadia-Alpha-PR484-ecbab2f.tar_06010dbc.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR484/Vircadia-Alpha-PR484-ecbab2f_06010dbc.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR484/Vircadia-Alpha-PR484-ecbab2f.tar_06010dbc.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR484/Vircadia-Alpha-PR484-ecbab2f_06010dbc.exe

**Comment by languagelovr** [comment]
This works perfectly. I tried turning it off and on a few times and it works in real-time, no delays. Thank you! 👍

**Comment by kasenvr** [comment]
Can be merged after terms of service and privacy policy are deployed.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR484/Vircadia-Alpha-PR484-a0efb03_52389e58.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR484/Vircadia-Alpha-PR484-a0efb03.tar_52389e58.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR484/Vircadia-Alpha-PR484-a0efb03.tar_52389e58.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR484/Vircadia-Alpha-PR484-a0efb03_52389e58.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR484/Vircadia-Alpha-PR484-a0efb03_52389e58.exe

**Comment by JulianGro** [comment]
We should probably add Vircadia copyright lines.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR484/Vircadia-Alpha-PR484-256bf40_8dd8ebcb.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR484/Vircadia-Alpha-PR484-256bf40_8dd8ebcb.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR484/Vircadia-Alpha-PR484-25d60a6.tar_989cd2d1.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR484/Vircadia-Alpha-PR484-25d60a6_989cd2d1.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR484/Vircadia-Alpha-PR484-25d60a6.tar_989cd2d1.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR484/Vircadia-Alpha-PR484-25d60a6_989cd2d1.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR484/Vircadia-Alpha-PR484-25d60a6_989cd2d1.exe

**Pull request merged**
