### PR TITLE
Change strings, comments and folders to Vircadia rebrand

### PR DESCRIPTION
**Pull request by JulianGro**
This PR changes some strings, folders and comments from "High Fidelity" to "Vircadia".
While most of the rebranded components seem unused to me, this PR should fix the Interface showing up as "High Fidelity" on macOS.

I will try building and running this on macOS.
EDIT: my macOS broke so I will not try building and running on macOS..

### CODE REVIEW

**Comment by ArcadeFever** [comment]
FWIW I was able to checkout this PR, build it successfully, and run Interface without a problem on MacOS.  If there is something you want me to verify, let me know.

**Comment by JulianGro** [comment]
@ArcadeFever when you run the interface, on the top left in the macOS bar thingee, it should say Vircadia now instead of High Fidelity now.

**Comment by ArcadeFever** [comment]
Confirmed, it now says Vircadia! :)

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR524/Vircadia-Alpha-PR524-9969af2.tar_dce34b8d.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR524/Vircadia-Alpha-PR524-9969af2.tar_dce34b8d.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR524/Vircadia-Alpha-PR524-9969af2_dce34b8d.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR524/Vircadia-Alpha-PR524-9969af2_dce34b8d.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR524/Vircadia-Alpha-PR524-9969af2_dce34b8d.exe

**Comment by languagelovr** [comment]
I can confirm everything looks good aside from the folder which still has the HiFi logo on it :)

Screen_Shot_2020-07-12_at_20 43 56

**Comment by JulianGro** [comment]
> I can confirm everything looks good aside from the folder which still has the HiFi logo on it :)
> 
> Screen_Shot_2020-07-12_at_20 43 56

@languagelovr I don't actually have any program that can change these files (probably because it is a proprietary format that is not used outside of macOS). If you or someone else wants to change that, they should be in interface/icon/

**Comment by languagelovr** [comment]
> > I can confirm everything looks good aside from the folder which still has the HiFi logo on it :)
> > Screen_Shot_2020-07-12_at_20 43 56
> 
> @languagelovr I don't actually have any program that can change these files (probably because it is a proprietary format that is not used outside of macOS). If you or someone else wants to change them, they should be in interface/icon/

I checked but do not see anything there. Perhaps it's in another location. I'll try to find it later though :)

**Pull request merged**
