### PR TITLE
Prevent a crash for corrupted GLTF models.

### PR DESCRIPTION
**Pull request by kasenvr**
This solves a crash reported by Odysseus where when a corrupt GLTF model in the cache tried to load, the interface would crash every time. This could be corrected by clearing the caches, now the behavior is where it will simply not load and output a warning in the log.

I have found in my testing that on first load into a corrupt domain the safeLandings may not disengage, you have to navigate away and come back in order to use the domain with the corrupted model on it.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR480/Vircadia-Alpha-PR480-87a248c_71fec167.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR480/Vircadia-Alpha-PR480-87a248c.tar_71fec167.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR480/Vircadia-Alpha-PR480-87a248c_71fec167.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR480/Vircadia-Alpha-PR480-87a248c.tar_71fec167.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR480/Vircadia-Alpha-PR480-87a248c_71fec167.exe

**Comment by JulianGro** [comment]
I cannot confirm this working by manually corrupting a glTF.
This is the original: http://94.130.177.235/%23480/cube.gltf
This is the "corrupted": http://94.130.177.235/%23480/cube_corrupted.gltf
I just changed the indices value from 3 to 3000, which from my understanding should trigger this exact crash.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR480/Vircadia-Alpha-PR480-eb33905_fe7f89cc.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR480/Vircadia-Alpha-PR480-eb33905_fe7f89cc.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR480/Vircadia-Alpha-PR480-eb33905.tar_fe7f89cc.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR480/Vircadia-Alpha-PR480-eb33905.tar_fe7f89cc.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR480/Vircadia-Alpha-PR480-eb33905_fe7f89cc.exe

**Comment by kasenvr** [comment]
The model you created to test the crashing was not the same issue that triggered the crash that this PR originally fixed. However, we pushed a commit to fix this new one as well. 2 for 1! :D

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR480/Vircadia-Alpha-PR480-1eaa5c9_fe0109aa.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR480/Vircadia-Alpha-PR480-1eaa5c9.tar_fe0109aa.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR480/Vircadia-Alpha-PR480-1eaa5c9.tar_fe0109aa.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR480/Vircadia-Alpha-PR480-1eaa5c9_fe0109aa.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR480/Vircadia-Alpha-PR480-1eaa5c9_fe0109aa.exe

**Comment by kasenvr** [comment]
Can you retest @JulianGro ?

**Comment by JulianGro** [comment]
Oh yes I did. It does not crash anymore.

**Pull request merged**
