### PR TITLE
NSIS: uncheck by default sandbox autostart

### PR DESCRIPTION
**Pull request by kasenvr**

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR596/Vircadia-Alpha-PR596-0d327a4.tar_5caec39c.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR596/Vircadia-Alpha-PR596-0d327a4_5caec39c.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR596/Vircadia-Alpha-PR596-0d327a4.tar_5caec39c.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR596/Vircadia-Alpha-PR596-0d327a4_5caec39c.dmg

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR596/Vircadia-Alpha-PR596-0d327a4_5caec39c.exe

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR596/Vircadia-Alpha-PR596-0d327a4.tar_5caec39c.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR596/Vircadia-Alpha-PR596-0d327a4_5caec39c.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR596/Vircadia-Alpha-PR596-0d327a4.tar_5caec39c.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR596/Vircadia-Alpha-PR596-0d327a4_5caec39c.dmg

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR596/Vircadia-Alpha-PR596-b6caf4e.tar_8061c5ab.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR596/Vircadia-Alpha-PR596-b6caf4e.tar_8061c5ab.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR596/Vircadia-Alpha-PR596-b6caf4e_8061c5ab.sh

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR596/Vircadia-Alpha-PR596-b6caf4e_8061c5ab.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR596/Vircadia-Alpha-PR596-b6caf4e.tar_8061c5ab.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR596/Vircadia-Alpha-PR596-b6caf4e_8061c5ab.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR596/Vircadia-Alpha-PR596-b6caf4e.tar_8061c5ab.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR596/Vircadia-Alpha-PR596-b6caf4e_8061c5ab.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR600/Vircadia-Alpha-PR600-ae147f7_04653c27.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR596/Vircadia-Alpha-PR596-36f0af3.tar_04653c27.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR596/Vircadia-Alpha-PR596-36f0af3.tar_04653c27.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR596/Vircadia-Alpha-PR596-36f0af3_04653c27.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR600/Vircadia-Alpha-PR600-ae147f7_04653c27.exe

**Comment by ctrlaltdavid** [comment]
Express install on one PC:
- Installed Interface and domain server.
- It did not started domain server. :)
- It did not downloaded domain server content. :)
- It did not run the oven. :)
- It automatically started Interface.
After rebooting PC:
- Server console did NOT automatically start up. :)

Custom install on a different PC:
- Install Interface and Sandbox: both options default selected.
- Launch Vircadia Sandbox after install: option NOT default selected. :)
- Launch Vircadia Sandbox on startup: option NOT default selected. :)
- It automatically started Interface.
After rebooting PC:
- Server console did NOT automatically start up. :)

**Pull request merged**
