### PR TITLE
Merge HiFi master

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
This PR seeks to merge HiFi's master into a "master-merge" branch off kasen/core.

Initial tests:
[ ] Does it build and generally run OK for people on Windows? Interface and Sandbox. And installer.
[ ] Does it build and generally run OK for people on on Linux? Interface and Sandbox.

Once merged into "master-merge", the "master-merge" branch can be used in the creation of a new, "master" branch for the repo. (Two ways to accomplish this.)

Note: GitHub Actions CI builds in this PR are not expected to work. These arise from HiFi's GitHub Actions work included in HiFi master, but they need to be fixed up for the Vircadia repo per Thoys's work in PR https://github.com/kasenvr/project-athena/pull/52.

### CODE REVIEW

**Comment by MarcusLlewellyn** [comment]
Unofficial PR build for Windows available here: [ProjectAthena-Alpha-PR285-.exe](https://cdn.vircadia.com/dist/pr-builds/ProjectAthena-Alpha-PR285-.exe)

**Comment by MarcusLlewellyn** [comment]
This fails to configure almost immediately on Ubuntu because of a deprecated python method in the module `distro` and the method `linux_distribution`. Dale Glass has fixed this in PR #53.

**Comment by MarcusLlewellyn** [comment]
Updated unofficial PR build for Windows here: [ProjectAthena-Alpha-PR285-1a4bb41f.exe](https://cdn.vircadia.com/dist/pr-builds/ProjectAthena-Alpha-PR285-1a4bb41f.exe)

**Comment by kasenvr** [comment]
I can confirm that after running CMake, I could successfully build Release and Debug, Release ran successfully. There were no immediate bugs that I could see but I did not do any in-depth testing of features to confirm.

**Comment by MarcusLlewellyn** [comment]
Updated unofficial PR build for Windows available here: [ProjectAthena-Alpha-PR285-a1df220.exe](https://cdn.vircadia.com/dist/pr-builds/ProjectAthena-Alpha-PR285-a1df220.exe)

**Comment by ctrlaltdavid** [comment]
The change log for the HiFi merges to master post 0.86:
[HiFi Post-0.86.0 Change Log.html.zip](https://github.com/kasenvr/project-athena/files/4519943/HiFi.Post-0.86.0.Change.Log.html.zip)

**Pull request merged**
