### PR TITLE
Enable username or e-mail for domain login

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Testing

Doman login:
- Placeholder text in login dialog should now say "Username or Email" (instead of just "Username").
- You should be ab le to log in with both username and e-mail address.

Metaverse login: No change. Placeholder text should still say "Username or Emai" and you should still be able to login with both username and e-mail address.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR852/Vircadia-Alpha-PR852-dbba1fe.tar_e28b2025.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR852/Vircadia-Alpha-PR852-dbba1fe_e28b2025.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR852/Vircadia-Alpha-PR852-dbba1fe.tar_e28b2025.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR852/Vircadia-Alpha-PR852-dbba1fe_e28b2025.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR852/Vircadia-Alpha-PR852-dbba1fe_e28b2025.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR852/Vircadia-Alpha-PR852-7359cfb_26405300.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR852/Vircadia-Alpha-PR852-7359cfb.tar_26405300.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR852/Vircadia-Alpha-PR852-7359cfb.tar_26405300.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR852/Vircadia-Alpha-PR852-7359cfb_26405300.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR852/Vircadia-Alpha-PR852-7359cfb_26405300.exe

**Comment by kasenvr** [comment]
Being connected via email acts very weirdly, for example... 

Even with my username + email added to the connect perms in the domain-server panel, it still won't let me into the server though it did log me in. However, if I log in with my username it will let me through. If I then proceed to log in with my email while connected, it will give me a connection error for the server, though it won't boot me and I will still see 6 servers connected in my stats.

Also a side-note: the domain login menu item does not change to "log out" if you are logged in and on the specific domain, but I assume that's just not implemented yet. :)

**Comment by Steve-Pruneau** [comment]
PR 852 has passed testing. I recommend it be included in the next release. I am referring to **server version PR852 - 7359cfb**. PR852 includes a change to both server and interface, which allows users to sign-in to a domain using either the user's Wordpress username or their email (when the OAuth MiniOrange Wordpress plug-in is used as the identity provider). Server and Interface were tested. Thanks to **CtrlAltDavid** for assistance during testing.

**Review by kasenvr — APPROVED** [review]

**Pull request merged**
