### PR TITLE
Bugfix: Add null check to entity render clearing to fix crash.

### PR DESCRIPTION
**Pull request by kasenvr**
Fixes https://github.com/kasenvr/project-athena/issues/407

### CODE REVIEW

**Comment by kasenvr** [comment]
@AleziaKurdis Does this fix the crashes for you?

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR409/ProjectAthena-Alpha-PR409-613fb19_94c230b7.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR409/ProjectAthena-Alpha-PR409-613fb19.tar_94c230b7.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR409/ProjectAthena-Alpha-PR409-613fb19.tar_94c230b7.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR409/ProjectAthena-Alpha-PR409-613fb19_94c230b7.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR409/ProjectAthena-Alpha-PR409-613fb19_94c230b7.exe

**Comment by AleziaKurdis** [comment]
This does fix the crash.

But I noticed that while I made the test:
there's a weird bloom effect with that **PR409**:

PR409_bloom issue

that wasn't present in **K2**, **K3Q** and **PR414**
K2_No_bloom issue

**Comment by kasenvr** [comment]
@HifiExperiments What do you make of that?

**Comment by kasenvr** [comment]
image
I am unable to immediately recreate this bug using this PR build and the steps outlined in issue #407.

**Comment by kasenvr** [comment]
@AleziaKurdis had an odd visual bug but I was unable to reproduce it. Because of this, we'll just go ahead and merge it because it seems like a trivial change anyway. At least we have documented and taken images of this specific issue and its potential relation to this PR, so if it shows up again then we know where to look. :)

**Pull request merged**
