### PR TITLE
GHA builds for merges to master

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
This uses GitHub Actions to automatically do the following:
- Build Windows, OSX, and Linux for each merge to master.
- Upload Windows and OSX installers to https://athena-public.s3-eu-west-3.amazonaws.com/master/[build-number]/Vircadia-Alpha-[build-number]-[commit-hash].exe/.dmg

Note: Target branch needs to be updated prior to merging.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Notes
- Currently configured to build pushes to the PR branch, `gha-master-ci`. This must be changed to `master` prior to merging the PR.
- Results can be viewed in GitHub's "Actions" tab. Find and click on the relevant "Master CI Build" item. Then click on the Windows / OSX / Linux item to see the build result.
- The URLs of the files uploaded to S3 is reported in the GitHub Actions log files. On one of the OS builds' pages, click the "..." top right of the dark area to expose the "Download log archive" and use this to download a zip of the build log files to view.
- OSX is built even though no installer for it is uploaded, as a check that OSX builds OK for the merge.

### Testing
- Downloaded and install he builds generated.
- Check that the installed builds work.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR719/Vircadia-Alpha-PR719-6f0f9c0_2ed37d0c.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR719/Vircadia-Alpha-PR719-6f0f9c0.tar_2ed37d0c.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR719/Vircadia-Alpha-PR719-6f0f9c0_2ed37d0c.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR719/Vircadia-Alpha-PR719-6f0f9c0.tar_2ed37d0c.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR719/Vircadia-Alpha-PR719-6f0f9c0_2ed37d0c.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR719/Vircadia-Alpha-PR719-807848b_90a7c6cd.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR719/Vircadia-Alpha-PR719-807848b.tar_90a7c6cd.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR719/Vircadia-Alpha-PR719-807848b.tar_90a7c6cd.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR719/Vircadia-Alpha-PR719-807848b_90a7c6cd.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR719/Vircadia-Alpha-PR719-807848b_90a7c6cd.exe

**Review by kasenvr — APPROVED** [review]
Worked fine for me on Windows 10!

One note @daleglass the master and PR builds folders should be publicly listable so it can be parsed by third-party apps or just by people browsing it. :)

**Pull request merged**
