### PR TITLE
renderWithZones works on import from JSON

### PR DESCRIPTION
**Pull request by HifiExperiments**
fixes https://github.com/kasenvr/project-athena/issues/562

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR564/Vircadia-Alpha-PR564-39ff487_1c8f783b.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR564/Vircadia-Alpha-PR564-39ff487_1c8f783b.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR564/Vircadia-Alpha-PR564-39ff487.tar_1c8f783b.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR564/Vircadia-Alpha-PR564-39ff487.tar_1c8f783b.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR564/Vircadia-Alpha-PR564-39ff487_1c8f783b.exe

**Comment by SilverfishVR** [comment]
tested with entities and models, parented and not parented to zone, and with multiple zones all seems to work 👍
we just want to make sure that it is understood that only zones included in the json is applied.

**Comment by HifiExperiments** [comment]
@SilverfishVR what do you mean?  if you import a JSON but there are other zones around, those other zones will still have an effect

**Comment by SilverfishVR** [comment]
no, if the json you imported did not include a zone referenced in one of the entities, it will be ignored, no weird errors shown, just ignored.
I think it's completely reasonable, json is supposed to self contained so if a user makes a json that relies on content already being present in the domain it can not be expected to work, so I consider this fixed

**Comment by HifiExperiments** [comment]
ah yeah it culls out values that it can’t convert since there’s no way they’ll point to the right thing.  I think parentID works the same way

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR564/Vircadia-Alpha-PR564-aab829a_1c8f783b.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR564/Vircadia-Alpha-PR564-aab829a_1c8f783b.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR564/Vircadia-Alpha-PR564-aab829a.tar_1c8f783b.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR564/Vircadia-Alpha-PR564-aab829a.tar_1c8f783b.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR564/Vircadia-Alpha-PR564-aab829a_1c8f783b.exe

**Pull request merged**
